### ISSUE TITLE
dumb question: how to make multi-line files?

### ISSUE THREAD

**Issue by i-make-robots** [finnp/create-file-action#10]
an example with the correct syntax in the readme would be great.
thank you!  stay awesome!

**Comment by finnp** [comment]
Something like `cat filename | base64`. Added it to the readme. Thanks

**Comment by dsherret** [comment]
Is there a recommended way to do this inline without having a file on the disk? (Also, why would someone use this action like `cat filename | base64` when the file is already created?)

While writing this question, I've opted to just do:

```
- name: Create file
  run: |
    echo "Line 1" > file.txt
    echo "Line 2" >> file.txt
    echo "Line 3" >> file.txt
```
